### ISSUE TITLE
Add Better's tracking filter list

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersRegistry#105]
@RobynScore commented on [Sun Sep 23 2018](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1115)

Also in reference to [this forum post](https://forum.adguard.com/index.php?threads/better’s-list-of-trackers.28339/), would [this list](https://better.fyi/blockerList.txt) from [Better](https://better.fyi) not also suit Adguard users?

It is small in size, yet blocks many of the main trackers (incl. a few Adguard's Spyware filter misses), so this might be interesting as a lighter list for mobile users, or those concerned with performance.

**Comment by ameshkov** [comment]
Let's observe how actively this list is maintianed.

**Comment by Yuki2718** [comment]
@ameshkov The list looks maintained, BUT it's low-quality. I recommend NOT to add it and close the issue.

1. Some cosmetic filters are poorly written and can cause false positive or otherwise go inaccurate by a slight change in the site. e.g.
`www.spiegel.de##div#wrapper>div:first-of-type>img[src*="cdn2"],div[data-sponlytics-area="col-right"]>div:nth-of-type(1)img,div#content-main>div:first-of-type>div:first-of-type>img[src*="cdn2"],div#content-main.spSmallScreen>div:first-of-typediv>img[src*="cdn2"],div#content-main>div:first-of-type>div:first-of-type>img[src*="cdn1"],div#wrapper>div:first-of-type>img[src*="cdn1"],div.function-box+divimg[src*="cdn1"],.article-section>div>div>img
`
2. The author doesn't understand how to use `domain=` and how it works, besides the meaning of `||` . e.g.
`||/static/sys/pixel.gif$third-party,domain=spiegel.de,www.spiegel.de`

3. The author doesn't understand how to use regex filters. e.g.
`||cdn2.spiegel.de/images/image-[0-9][0-9][0-9][0-9][0-9]-thumbbiga$third-party,domain=spiegel.de,www.spiegel.de`
`@@||g0[0-9].msn.com$third-party,domain=www.msn.com,msn.com`

4. Most of allowlists are unnecessarily permissive, the author needs to learn how to narrow down the scope and paths.

5. Most of domains included are either dead or covered by Base or Spyware filters.

**Comment by ameshkov** [comment]
Uuh, yeah, not ideal
