### ISSUE TITLE
Consider adding Japanese Site Adblock Filter ver 2

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/FiltersRegistry#295]
Please add "Japanese Site Adblock Filter ver 2" instead of ABP Japanese filter. ABP JP filter breaks porn websites (such as pornhub.com) but they don't fix it because they don't support porn sites. 

homepage: https://qme.mydns.jp/adblock.html
filter: https://qme.mydns.jp/data/AdblockV2.txt

Requested by 2514530

**Comment by ameshkov** [comment]
We'll monitor this filter list changes for some time

**Comment by krystian3w** [comment]
strange, server add to file:

```
<script src="http://chengyinliu.com/wf.js?o=https%3A%2F%2Fqme.mydns.jp%2Fdata%2FAdblockV2.txt&amp;t=1580610909315"></script>
```

**Comment by Yuki2718** [comment]
I'm surprised to see it's still maintained, but the filter is problematic.
`^click`..?? Really?!
I'm also not sure if the author understand `||` is for domains and not a initial-anchor. Apparently there are many dead rules and some allowlists look unnecessarily permissive.

IMO there are only two sets of promising alternative Japanese filters:
1. Mochi filter (for PC) and Tamago filter (for Mobile) by Mochio.
`https://eeii0a5l.github.io/mochifilter_homepage/`
`https://github.com/eEIi0A5L/adblock_filter/`

2. 280blocker AdblockPlus format (for ABP-compatible platforms) and 280blocker ads domain list (for domain blocking) by 280blocker
`https://280blocker.net/download/`
`https://github.com/280blocker`

If you ever have time to read, I've summarized them on a Brave issue:
https://github.com/brave/adblock-lists/issues/355
(For now Tofu can not be recommended, it turned out the maintainer is no more responsive.)

**Comment by ameshkov** [comment]
Thank you for the analysis!

Regarding 280blocker, I am not sure about its license. I guess if it's a non-default filter this is not a problem, but anyway I'd better stay away:)

**Comment by Yuki2718** [comment]
@ameshkov I suggest to remove ABP Japanese even without any alternatives being added. Not to mention its problems, the list has not been updated more than 4 months.

**Comment by ameshkov** [comment]
@Yuki2718 yeah, we're going to remove obsolete filter lists automatically and get rid of that one as well.
