### ISSUE TITLE
Add Futa Filter (for AG and AG Home)

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/FiltersRegistry#430]
https://github.com/FutaGuard/FutaFilter
The lists are overall good and worth adding.

**Comment by ameshkov** [comment]
1. I see that https://filter.futa.gg/filter.txt uses JS rules which we generally don't allow in third-party lists (unless they are installed as custom trusted lists). @tasi788 can these JS rules be converted to scriptlets or to other rule types?
2. Could you please come up with an English name and description that we can use?
3. I generally like the $removeparam list and I think it'd be nice to have it in the "Privacy" group, but in order to do that, there should be a homepage/repo with an English description. The list seems to be "global" enough to not be placed in the regional lists. This is up to you, of course.

**Comment by tasi788** [comment]
1. we've tried using [scriptlet](https://github.com/AdguardTeam/Scriptlets) instead, check here.
https://github.com/FutaGuard/FutaFilter/commit/6592053259f723799c8356a66859d62852c6f0a7#diff-2b332613793173c8760f7c21faa3b9e3543b3a2329b1a51108993345ded05dbf
2. FutaFilter that specifically Taiwan users, including sms scam links, ads ... etc
3. maybe I can adding a new wiki page in repo, If this is ok.

**Comment by tasi788** [comment]
Title: FutaFilter List
Description: an advertisement blocking list specialized for Taiwanese users.
Homepage: https://github.com/FutaGuard/FutaFilter/blob/master/README.en.md

Title: FutaFilter removeparam List
Description: Now the tracker is proliferating and can be seen everywhere. This list designed to against URL tracks, protect users privacy.
Homepage: https://github.com/FutaGuard/FutaFilter/blob/master/README.en.md

**Comment by ameshkov** [comment]
Thank you!

@Alex-302 could you please open a PR?

Also, for the `FutaFilter URL Privacy Guardner List` we may need to wait until FiltersCompiler is finally updated. Same thing as with @DandelionSprout's #401 -- we need a way to not exclude it from iOS/Safari/etc filter lists.

**Comment by c2xusnpq6** [comment]
`Adguard Taiwanese`? @ameshkov @AdguardTeam

**Comment by DandelionSprout** [comment]
Personally, I feel that regional lists need at least 200 entries before inclusion, if their languages has more than 1 million speakers.

I'm also unsure if the maintainer knows the Western meaning of the word "futa".

**Comment by Yuki2718** [comment]
> 
> I'm also unsure if the maintainer knows the Western meaning of the word "futa".

OMG I didn't know too.

**Comment by tasi788** [comment]
@DandelionSprout 

We knows what "futa" meaning actually. 
When we created this rule, the [Interspecies Reviewers](https://myanimelist.net/anime/40010/Ishuzoku_Reviewers) (may contain NSFW content not sure) anime was very popular in Taiwan. and theres a cute character called "Crimvael", and our team really like [ze](https://www.lexico.com/definition/ze) so our team agreed that this list should be called "futafilter"

Please let us know if the word "futa" is potentially offensive, and we plan to add the "futafilter" naming convention to the readme of the repo.

**Comment by DandelionSprout** [comment]
Ah. It's not actually considered offensive in general settings, but it can cause some "LOL" and "Uh..."

**Comment by DandelionSprout** [comment]
As for the amount of entries, spending a few hours going through the top ~200 sites of https://domaintyper.com/top-websites/most-popular-websites-with-tw-domain, can increase the amount of entries a bit.

**Comment by tasi788** [comment]
> As for the amount of entries, spending a few hours going through the top ~200 sites of https://domaintyper.com/top-websites/most-popular-websites-with-tw-domain, can increase the amount of entries a bit.

Thanks for the suggestion, I am planning to add more rules during work breaks.

**Comment by zloyden** [comment]
@tasi788 Hi! I have looked at your filters and they are good. Note, that your list contains some JS rules and they won't work in our products due to trust-level option.
In that case, you can exchange some of them. Please see our [scriptlets](https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#scriptlets).
For instance, this `udn.com#%#if (typeof localStorage != 'undefined' && localStorage.setItem) { localStorage.setItem('bd2021-read-news', '1'); }` should work fine like this.
```
udn.com##%#//scriptlet('set-local-storage-item', 'bd2021-read-news', '1')
```

> Please let us know if the word "futa" is potentially offensive, and we plan to add the "futafilter" naming convention to the readme of the repo.

I don't think that we can use `futa` in the filter name. Do you have any alternatives?

**Comment by zloyden** [comment]
@tasi788 https://filter.futa.gg/filter.txt
Doesn't seem to have been updated. If you still maintain this, please write in this task.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/180184022-2f967808-e7b8-4cff-abfe-9066ee2415d2.png)

</details><br/>

**Comment by tasi788** [comment]
> 
I will find time to read and update it recently

**Comment by tasi788** [comment]
Hi @zloyden, 
I've add more rule kill ads, tacker and remove javascript in list. and we've rename `FutaFilter` to `LowTechFilter`. Please let me know if there any idea & problem we need to do.
https://github.com/FutaGuard/FutaFilter/commits/master
