### ISSUE TITLE
Add ExperimentalNorwegianList to the list of subsciptions

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersRegistry#48]
@Eugene-Savenko commented on [Tue Apr 17 2018](https://github.com/AdguardTeam/AdguardFilters/issues/14877)

https://github.com/DandelionSprout/adfilt/blob/master/NorwegianList.txt

**Comment by DandelionSprout** [comment]
Thank you for adding my list to Adguard. It feels nice to see that you felt it met the criteria for inclusion there.

After doing some research in a hurry, I do however notice that it's so far only been added to the desktop (e.g. Windows and Mac) versions of Adguard, and not to the [browser extensions](https://github.com/AdguardTeam/AdguardBrowserExtension/blob/master/Extension/filters/chromium/filters.json) or the [Google Play](https://play.google.com/store/apps/details?id=com.adguard.android.contentblocker) version. Are there any particular reasons as to why that hasn't been done yet?

**Comment by ameshkov** [comment]
Hi and thank you for maintaining a filter, this is a big deal!

Browser extensions list of known filters is updated when we build a new version of the extension and it's about to happen.

Regarding the Android (both content blocker and the full version), the list of available filters there is hardcoded for now. We'll change it and let it update dynamically in a future update. 

> I do however notice that it's so far only been added to the desktop (e.g. Windows and Mac) versions of Adguard

Please let us know if you'd like to get a license key for the desktop/Android/iOS versions of AG by sending a message to `devteam at adguard.com`, we'd be happy to provide it to a filters maintainer.

**Comment by DandelionSprout** [comment]
Ah, okay, thanks for the info and compliments. I'll look forward to its inclusion in the browser extensions soon, then. 👍 

Earlier this morning I received an E-mail from a Norwegian user of Content Blocker who told me that he wasn't able to use my Norwegian list in that app, and that he allegedly wasn't able to import the list's URL either, so that too was a factor for why I commented on this thread.

>Please let us know if you'd like to get a license key for the desktop/Android/iOS versions of AG by sending a message to devteam at adguard.com, we'd be happy to provide it to a filters maintainer.

While I'm normally using Nano Adblocker and uBO, an Adguard licence would be invaluable for occasional testing purposes and for personal use, so I've sent an E-mail to that E-mail address now. 🙂

**Comment by ameshkov** [comment]
> While I'm normally using Nano Adblocker and uBO, an Adguard licence would be invaluable for occasional testing purposes and for personal use with e.g. IE and Steam, so I've sent an E-mail to that E-mail address now. 🙂

Done, thank you!

**Comment by DandelionSprout** [comment]
It's okay, I received an E-mail reception notification for it either way. 🙂
