### ISSUE TITLE
Filters linter

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersRegistry#520]
I'd like us to have a filters linter (just like there's `eslint` for JS or all kinds of linters for `golang`).
Once we have it, we can have a Github action that runs it on every commit.

@zloyden please come up with a spec, use https://eslint.org/ as a reference

1. What rules this linter should have?
2. What would be the command-line interface?

**Comment by zloyden** [comment]
Hi! Global tasks that have to be done.
1. The linter should cover all type of our rules: basic - simple cosmetic `##` -> `example.com##body` and blocking request rules like `||example.com^$third-party`;
rules with using extended-css support `#?#` -> `example.com#?#.widget:has(> div.banner)`;
css rules `#$#` -> `example.com#$#body { background: none !important; }`;
scriptlets `#%#//scriptlet()` and JS rules `#%#`;
HTML rules `thestreet.com$$script[tag-content="welcomeOverlay"][max-length="8000"]`.
There is also should be validation whether the rules apply to certain sections of the filter. For instance, let's take a look at sections of the AdGuard Base filter:
`adservers.txt`, `adservers_firstparty.txt` - only blocking request rules -> we have wide rules (block domains or subdomains) like `||example.com^` or `||ads.example.com^` are correct, but `||example.com/banner/` is not;
`banner_sizes.txt` - only simple cosmetic rules `##`;
`css_extended.txt` - only rules with using `#?#`, pseudo-classes like `:has()` and without pseudo-classes;
`cryptominers.txt` - only blocking request rules;
`general_elemhide.txt` - only simple cosmetic rules `##` withour domain at the end, unless we use `~` before the domain like `##banner` or `~example.com##banner` are correct;
`general_extensions.txt` - only scriptlets, JS and HTML rules;
`general_url.txt` - only blocking request rules without specific domain at the beginning like `/banner/*` or `/images/ads/ads.js`;
`replace.txt` - only blocking request rules that having a modifier `$replace` are important;
`specific.txt` - basic rules without the modifiers `$replace`, `$stealth`;
`whitelist_stealth.txt` - blocking request rules using `@@||` at the beginning (exception rules) and there the modifier `$stealth` is important;
`whitelist.txt` - exception rules. `@@||` at the beginning of the blocking rule, such syntax for cosmetic rules `#@#`, `#@$#`, `#@?#`, `#@$?`, for scripltets `#@%#//scriptlet()`, for JS `#@%#`, HTML rules `$@$`.
 `UsefulAdsFilter` should only have exception rules, `news_exchange.txt` in the `AdGuard Russian` - only basic rules.
Also that validation should be disabled for the sections `antiadblock.txt`, `foreign.txt` and `AdGuard Annoyances` filter completely.

2. The linter has to have be compatible with MacOS (Terminal) and Windows (PowerShell) platforms.

---

**Some notes about checking  the rules.**

1.1. Basic rules. The linter should check such rules using this syntax https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#basic-rules. Please note, that we have to use only one selector in all type of cosmetic rules. `example.com##.banner` is correct, but this is not `example.com##.banner, .ad` and should be rewritten as two separated rules.
Also for the blocking rules that are using a modifier `$redirect=` we have to add at the beginning the type of the request. https://github.com/AdguardTeam/Scriptlets#redirect-resources
1.2. For `#?#` rules should use this syntax https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#extended-css-selectors. Rules without using pseudo-classes like `example.com#?#.banner` shouldn't be counted as an error.
1.3. For `#$#` rules should use this syntax https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#cosmetic-css-rules. `example.com#$#body { background-color: #333!important; }` or `example.com#$#body { background-color: #333 !important; }` are allowed to be written.
1.4. For scriptlets `#%#//scriptlet()` the linter has to check correct writitng of the scriptlet: his name and some specific values like we have for `example.org#%#//scriptlet('set-constant', property, value[, stack])`. For instance, `example.org#%#//scriptlet('set-constant', 'secondConst', 'trueFunc')` is correct, this is not `example.org#%#//scriptlet('set-const', 'secondConst', 'trueFunction')`. Mostly, there shouldn't be verification of quotes. Both of them are correct `example.org#%#//scriptlet('set-constant', 'secondConst', 'trueFunc')` or `example.org#%#//scriptlet("set-constant", "secondConst", "trueFunc")`.
But for the scriptets like `remove-class, remove-attr, remove-in-shadow-dom` that are using selector, the linter has to count using single quotation marks as the right option, otherwise such rule won't work `example.org#%#//scriptlet("remove-attr", "example", "div[class="inner"]")` because we have double quotes here `div[class="inner"]`. All information you can read here https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md.
For the JS rules we also should use `eslint`, but we have some specific functions https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/general_js_api.txt, that also should be included in the validation.
1.5. For `$$` rules use this syntax https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#html-filtering-rules.
