### ISSUE TITLE
Problem about Japanese filter name.

### ISSUE THREAD

**Issue by SKEIDs** [AdguardTeam/FiltersRegistry#562]
I think the name is weird.
Please insert a space.

For example: https://github.com/AdguardTeam/FiltersRegistry/blob/acbf2a498a83b4064194bf4b7f537caf94c1b51f/locales/ja/filters.json#L11
AdGuard追跡防止フィルタ → AdGuard 追跡防止フィルタ

**Comment by krystian3w** [comment]
Looks strange for native speakers?

**Comment by gork7777** [comment]
Thanks, I'll look into the Japanese translation

**Comment by SKEIDs** [comment]
> Looks strange for native speakers?

The names of the other filters are fine if they don't have spaces.
However, most of them do have spaces.
I think it's better to align them.
I think that is the same as this↓

AdGuard Base → AdGuardBase

Isn't this strange?

**Comment by vyanovsky** [comment]
The idea was that maybe without the space is better  because it's a name of the filter, "AdGuard Tracking Protection filter" = "AdGuard追跡防止フィルタ", like inseparable name.
With the space it might separate them slightly, so one might think that it's combination of two semantics, "AdGuard" and "追跡防止フィルタ", not one solid filter name.
But without the space it does look a bit strange.
Thank you for the feedback, we will think which one is better, and correct all AdGuard filter names accordingly.
If you have any further thoughts, we'd more than happy to hear them.

**Comment by SKEIDs** [comment]
I understand. Thank you.
