### ISSUE TITLE
For Icelandic, two filters are recommended

### ISSUE THREAD

**Issue by Einarsson1221** [AdguardTeam/FiltersRegistry#566]
For Icelandic users, "Dandelion Sprout's Nordic Filters" and "Icelandic ABP List" are recommended. These are good for one or the other, aren't they?

**Comment by krystian3w** [comment]
@DandelionSprout

**Comment by iam-py-test** [comment]
I have no idea. Let me fire up a VM and see if I can repro
@Einarsson1221 please provide AdGuard and browser versions

**Comment by iam-py-test** [comment]
Still need screenshots to confirm what you are talking about

**Comment by krystian3w** [comment]
I suppose he ask how many breakages generate turn on both.

Now we know AdGuard Russia and Ru AdList is incompatible vice-versa (one should be always disabled).

**Comment by DandelionSprout** [comment]
Despite *Icelandic ABP List*'s "Last updated" date being 23th of December 2021, my understanding is that most of that list hasn't been changed since circa 2016.

On that ground, I'd say that my list is somewhat better for Icelandic sites, despite me too having reached a soft limit for how many Icelandic sites there are out there that entries can be added for.

**Comment by ameshkov** [comment]
Here's a quick explanation on how "recommended" works:

AdGuard automatically enables recommended filter lists if it detects that you're visiting websites in that language. It will enable **all** recommended lists for that language.

How detection works:

1. Upon AG installation it checks your keyboard layouts and assumes that you're visiting websites in the given language if you have its layout.
2. While using AG it checks the language of the pages you're visiting (if this functionality is provided by the browser) OR it checks top-level domains of the visited websites (in this case you should visit them rather often, one domain is not enough to trigger auto-enabling of a filter list).

**Comment by Einarsson1222** [comment]
@krystian3w @iam-py-test @DandelionSprout @ameshkov 

I forgot my account password, so I had to recreate my account.

My reasons for launching this issue are as follows. When I visited the Icelandic website, two filters were automatically enabled. However, I don't need the "Icelandic ABP List" if "Dandelion Sprout's Nordic Filters" are enabled. So I thought you might want to consider removing your recommendation of the "Icelandic ABP List" so that this filter is not automatically enabled.

Thanks for your comment.

**Comment by iam-py-test** [comment]
> I forgot my account password, so I had to recreate my account.

Do you have a recovery email? You should be able to recover your account without your password

**Comment by krystian3w** [comment]
Maybe used 10 minutes mail, but GitHub fastly shadowban account and issues from that e-mail account.

**Comment by ameshkov** [comment]
Well, the question is can @DandelionSprout's list be a complete replacement for Icelandic ABP List. If it is, we're fine with keeping it the single recommended filter list.

**Comment by DandelionSprout** [comment]
It at least *aims* to be a complete replacement.

**Comment by ameshkov** [comment]
@zloyden please check this out

**Comment by zloyden** [comment]
Well, we can leave one recommended filter list.
