### ISSUE TITLE
Reconsider YousList

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/FiltersRegistry#691]
### Prerequisites

- [X] I checked the documentation and understood it;
- [X] I checked to make sure that this issue has not already been filed;

### Problem description

Currently, YousList is known as a Korean language filters list.
However, there are some issues with the filter list:

#### Outdated filters
https://github.com/hagezi/dns-blocklists/blob/main/usedsources.md#proplus reports that there are dead domains exist 39% of all.
Furthermore, I guess that useless rules including non-existent elements and request can exist 50% or higher of all.

#### Category issue
There are commits about non-Korean language website for hiding/blocking even if YousList is known as a Korean language filters list.
For example, The following domains are not related to Korean language website pushed during last 6 months:
 - https://www.inverse.com/ ( https://github.com/yous/YousList/commit/bd903d507bb9a12419b68572eb79b23ddd75fd2f )
- https://www.idownloadblog.com/ ( https://github.com/yous/YousList/commit/35e3e042175aa72f9e3ce2e7316406815daa980c )
- https://www.cpubenchmark.net/ ( https://github.com/yous/YousList/commit/172abdba0fe0a55110655c19e214ef1145ed5776 )
- https://www.bbc.com/ ( https://github.com/yous/YousList/commit/9c47d3bde9e2ec00b7524fd7940f7d2871b6c8fd )
- https://guitar.com/ ( https://github.com/yous/YousList/commit/1d743df769a604a58fc85a1ca2348d0a79818cbc )
- https://www.techradar.com/ ( https://github.com/yous/YousList/commit/a03e09b6c4b6cb07ed79f7a3e4ae1fbf3c43b22b )
- https://www.theserverside.com/ ( https://github.com/yous/YousList/commit/0d0fcd06b54c5e4c1cd9a588a8b6926dfcfd1258 )
- https://www.axios.com/ ( https://github.com/yous/YousList/commit/b60eb6643032eaa816b2327d6c068bb8fe86a35f )
- https://www.gsmarena.com/ ( https://github.com/yous/YousList/commit/2923fc2b047178d58be4e2a923c97b3f444b945a )
- https://www.outsideonline.com/ ( https://github.com/yous/YousList/commit/92603090889df92262874aeb731c4ab2a9628d4e )
- https://www.cnbc.com/world/?region=world ( https://github.com/yous/YousList/commit/436ff8c80cf1154d8e21a641796cb2d9998c3cf7 )

#### Commit activity issue
The number of Youslist's commits during last 6 months is 55.
But, contrastively, List-KR filter's is 1144.

#### Filters expression
The expression of filters in YousList is not optimized.
It means that many filters can be optimized by using one rule like the following example:
```adblock
spojoy.com##div#banner_left
spojoy.com##div#banner_left_160x600
spojoy.com##div#banner_right
online.anidub.com##div#banner_post2
online.anidub.com##div#banner_test
newsen.com##div#banner_wrap
news.tvchosun.com##div#banner_header
mediatoday.co.kr##div#banner_header_wide
itworld.co.kr##div#banner_bg
itworld.co.kr##div#banner_right_wing
itworld.co.kr##div#banner_top
mediatoday.co.kr##div#banner_header_wide
itworld.co.kr##div#banner_bg
itworld.co.kr##div#banner_right_wing
itworld.co.kr##div#banner_top
hungryapp.co.kr##div#banner_11
hungryapp.co.kr##div#banner_new
daejonilbo.com##div#banner_main_right180
ciokorea.com##div#banner_bg
ciokorea.com##div#banner_right_wing
ciokorea.com##div#banner_top
```

### Proposed solution

Remove YousList from AdGuard's FiltersRegistry repository like uBO community did.

**Comment by piquark6046** [comment]
CC: @yous

**Comment by piquark6046** [comment]
I think that this discussion is very important for many users living in South Korea.
Because, A NamuWiki article related to AdGuard recommends YousList if an user wants better filtering.[^1][^2]
NamuWiki website is the most famous wiki in South Korea [^3] even if the following issues exist:
- Editors of NamuWiki articles do not attach a proper reference well like Wikipedia's do.
- Umanle S.R.L., owner of NamuWiki, violates their own promise about what Umanle S.R.L. will not perform the anti-adblock script.

[^1]: `한국어 웹 사이트용 필터는 List-KR이 내장되어 있다. 보다 철저한 필터링을 원한다면 서드파티 필터인 Youslist가 있다.` at https://namu.wiki/w/AdGuard#s-11 and Dec 3, 2022
[^2]: The description was added by [gradientoverlay](https://namu.wiki/w/%EC%82%AC%EC%9A%A9%EC%9E%90:gradientoverlay) at Nov 26, 2021.[View diff](https://namu.wiki/diff/AdGuard?rev=536&oldrev=535)
[^3]: https://www.similarweb.com/website/namu.wiki/#traffic

**Comment by ameshkov** [comment]
This is actually a wider question.

Historically, we allowed multiple lists for a single language as long as these lists do not conflict with each other. There are many examples (several Polish lists, List-KR and YousList, etc).

> There are also a bit different examples: AdGuard German filter and EasyList Germany. AdGuard German filter is basically EasyList Germany + AdGuard rules which is explained in the filter description, however the user may opt to choose just the EasyList Germany.

That's why we added a different distinction, a "recommended" mark to let people know which list we think would better work with AdGuard. There can be only one recommended language-specific filter list and currently, List-KR is marked as "recommended" in AdGuard.

So the big question is: should we change our policy to language-specific lists and limit it to "1 language - 1 list"?

**Comment by piquark6046** [comment]
> should we change our policy to language-specific lists and limit it to "1 language - 1 list"?

No. I don't want to change the policy about language-specific filters lists.
What I want is literally removing YousList from FitlersRegistry repository.

> That's why we added a different distinction, a "recommended" mark to let people know which list we think would better work with AdGuard.

However, there are some comments and posts of internet communities that tells that use YousList instead of List-KR filter because of anti-adblock behavior of Umanle S.R.L.
- https://www.clien.net/service/board/park/17196723
- https://meeco.kr/mini/35165916

The following cases are not related to the behavior, but YousList is recommended:
- `comment#comment_35471159` in https://meeco.kr/mini/35470394
- https://www.clien.net/service/board/cm_iphonien/17153546?c=true#134143368
- https://meeco.kr/mini/34940569
- https://www.clien.net/service/board/cm_iphonien/17477379?c=true#137089770

In additional, the four issues exist.

**Comment by yous** [comment]
I don't understand why do you want to remove an option for Korean, while saying this issue is important for users in Korea.

They are individual users having their own experiences. Some of their arguments may be wrong, but some of them may be right. Why do you think recommending a filter list is a reason to remove that list from FilterRegistry?

**Comment by ameshkov** [comment]
> What I want is literally removing YousList from FitlersRegistry repository.

We have rather strict requirements about lists inclusion: https://github.com/AdguardTeam/FiltersRegistry#what-filters-can-be-added-to-this-repository

As I understand YousList is a popular Korean list and it satisfies the requirements. What grounds are there for removing it? If it does not, which ones exactly are not satisfied?

> However, there are some comments and posts of internet communities that tells that use YousList instead of List-KR filter because of anti-adblock behavior of Umanle S.R.L.

This is not the fault of YousList, rather this is a misunderstanding by the people that are posting it, right?
If the posts are misleading, they can be addressed right there on these forums or in List-KR description.
Also, even if the filter list is not in among preinstalled anymore, people still can read those posts and install it.

In our history we only had such an issue once. We had two russian filter lists - RU AdList and AdGuard Russian list. The problem was that these lists were not compatible, i.e. using them both at the same time were causing more troubles than doing good. Moreover, this incompatibility created additional burden for both AdGuard maintainers and the RU AdList maintainer. At some point both AdGuard and RU AdList maintainers asked for the list removal just to reduce the possibility of people using incompatible lists.

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/FiltersRegistry/issues/691#issuecomment-1336959382

Here you are.
https://github.com/List-KR/List-KR/graphs/commit-activity
https://github.com/yous/YousList/graphs/commit-activity

**Comment by zloyden** [comment]
According to our rules (mentioned here https://github.com/AdguardTeam/FiltersRegistry/issues/691#issuecomment-1336491386),  the filter satisfies the requirements.
What about the `Outdated filters` and `Filters expression` https://github.com/AdguardTeam/FiltersRegistry/issues/691#issue-1473741821 @yous could you improve it?
I'm closing it for now.

**Comment by yous** [comment]
Yes, I'll look into it soon.
